#!/bin/bash

# This script creates a tmux session which is ideal for coding.
# The session has 1 window with three panes. 
# One pane runs "watch tree" to display an updated directory structure of your working directory.
# The main pane runs "Vim" for coding. 
# The third pane is for executing commands.



if [ -z $1 ] 
then
		echo "Needs an argument"
		echo "Usage $0 <session-name>"
else
		x=$(stty size | awk '{print $2}')
		y=$(stty size | awk '{print $1}')
		if [ -z $(tmux list-sessions | grep $1) ]
		then
				tmux set -g base-index 1
				tmux new -d -s $1 -x $x -y $y
				tmux select-window -t $1:1
				tmux split-window -h -p 75
				tmux select-pane -t 2 
				tmux split-window -v -p 25
				tmux select-pane -t 1 
				prevpath=$(tmux display-message -t 1 -p -F \"#{pane_current_path}\")
				tmux send-keys "lscwd $prevpath" C-m
				tmux select-pane -t 2
				tmux attach -t $1
		else
				echo "Session already exists with the name $1. Please try a different session name"
				exit 1
		fi
fi
