#!/bin/bash

# This script creates a tmux session which is ideal for coding.
# The session has 1 window with three panes. 
# One pane runs "watch tree" to display an updated directory structure of your working directory.
# The main pane runs "Vim" for coding. 
# The third pane is for executing commands.



if [ -z $1 ] 
then
		echo "Needs an argument"
		echo "Usage $0 <session-name>"
else
		x=$(stty size | awk '{print $2}')
		y=$(stty size | awk '{print $1}')
		if [ -z $(tmux list-sessions | grep $1) ]
		then
				tmux set -g base-index 1
				tmux setw -g pane-base-index 1
				tmux unbind C-b
				tmux set-option -g prefix C-a
				tmux bind-key C-a send-prefix
				tmux bind -n M-Left select-pane -L
				tmux bind -n M-Right select-pane -R
				tmux bind -n M-Up select-pane -U
				tmux bind -n M-Down select-pane -D
				tmux set-option -g allow-rename off
				tmux set -g status-position top
				tmux set -g status-justify left
				tmux set -g status-bg colour0
				tmux set -g status-fg colour202
				tmux set -g status-attr dim
				tmux set -g status-left ''
				tmux set -g status-right '#[fg=colour2,bg=colour0,bold] %d/%m #[fg=colour3,bg=colour8,bold] %H:%M:%S '
				tmux set -g status-right-length 50
				tmux set -g status-left-length 20
				tmux setw -g window-status-current-fg colour2
				tmux setw -g window-status-current-bg colour0
				tmux setw -g window-status-current-attr bold
				tmux setw -g window-status-current-format ' #I#[fg=colour249]:#[fg=colour255]#W#[fg=colour249]#F '
				tmux setw -g window-status-bell-attr bold
				tmux setw -g window-status-bell-fg colour255
				tmux setw -g window-status-bell-bg colour1
				tmux set -g message-attr bold
				tmux set -g message-fg colour232
				tmux set -g message-bg colour16
				tmux set-window-option -g mode-keys vi
				tmux bind-key -T copy-mode-vi 'v' send -X begin-selection
				tmux bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel
				tmux new -d -s $1 -x $x -y $y
				tmux select-window -t $1:1
				tmux split-window -h -p 75
				tmux select-pane -t 2 
				tmux split-window -v -p 25
				tmux select-pane -t 1 
				prevpath=$(tmux display-message -t 1 -p -F \"#{pane_current_path}\")
				tmux send-keys "lscwd $prevpath" C-m
				tmux select-pane -t 2
				tmux attach -t $1
		else
				echo "Session already exists with the name $1. Please try a different session name"
				exit 1
		fi
fi
